#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub(crate) enum ChangeType {
    DocsOnly,
    ExampleChange,
    SchemaChange,
    SchemaBreakingChange,
    RuntimeCodeChange,
    MultiPackageChange,
    ProviderContractChange,
    DependencyAddition,
    DependencyVersionChange,
    WorkflowChange,
    PublicApiChange,
    CredentialChange,
    SensitiveDataExposure,
    ReleaseChange,
    DeployChange,
    ValidatorSensitiveChange,
    ValidatorSelfBypass,
    FileDeletion,
    BulkMove,
    RiskPathChange,
    ExternalAccountChange,
    BudgetExceeded,
    UnknownHighRisk,
}

impl ChangeType {
    pub(crate) fn as_str(self) -> &'static str {
        match self {
            Self::DocsOnly => "docs_only",
            Self::ExampleChange => "example_change",
            Self::SchemaChange => "schema_change",
            Self::SchemaBreakingChange => "schema_breaking_change",
            Self::RuntimeCodeChange => "runtime_code_change",
            Self::MultiPackageChange => "multi_package_change",
            Self::ProviderContractChange => "provider_contract_change",
            Self::DependencyAddition => "dependency_addition",
            Self::DependencyVersionChange => "dependency_version_change",
            Self::WorkflowChange => "workflow_change",
            Self::PublicApiChange => "public_api_change",
            Self::CredentialChange => "credential_change",
            Self::SensitiveDataExposure => "sensitive_data_exposure",
            Self::ReleaseChange => "release_change",
            Self::DeployChange => "deploy_change",
            Self::ValidatorSensitiveChange => "validator_sensitive_change",
            Self::ValidatorSelfBypass => "validator_self_bypass",
            Self::FileDeletion => "file_deletion",
            Self::BulkMove => "bulk_move",
            Self::RiskPathChange => "risk_path_change",
            Self::ExternalAccountChange => "external_account_change",
            Self::BudgetExceeded => "budget_exceeded",
            Self::UnknownHighRisk => "unknown_high_risk",
        }
    }
}
